## David Lanza 2-19-25
## This code was generated by chatgpt 4o
## The Titlescreen waits for a button press and pops its state
## off of the state stack.

extends Control

var game_manager = null

func set_game_manager(manager):
	game_manager = manager

func _ready():
	print("Title Screen Loaded. Press any key to continue.")

func handle_input(event):
	if event is InputEventKey or event is InputEventMouseButton:
		if game_manager:
			game_manager.pop_state()
