## David Lanza 2-19-25
## This code was generated by chatgpt 4o
## it is a minimal starting point for a level.

extends Node

class_name LevelTemplate

var game_manager = null

func set_game_manager(manager):
	game_manager = manager

func _ready():
	pass

func handle_input(event):
	pass

func transition_to_next_level():
	if game_manager:
		game_manager.pop_state()
